name: merge

on:
  pull_request:
    branches: 
      - main
    types: [closed]

permissions:
  contents: read

jobs:
  cloudflare:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command:
            pages deploy . --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }} --branch=main

      - name: Purge Cache
        if: ${{ github.event.pull_request.merged }}
        uses: fishmanlabs/cloudflare-purge-cache-action@v1
        with:
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          purge_everything: 'true'
